
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner-sa
  namespace: {{ .Values.storeId }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: provisioner-role
  namespace: {{ .Values.storeId }}
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources:
      - deployments
      - services
      - ingresses
      - secrets
      - persistentvolumeclaims
    verbs: ["create", "delete", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: provisioner-binding
  namespace: {{ .Values.storeId }}
subjects:
  - kind: ServiceAccount
    name: provisioner-sa
roleRef:
  kind: Role
  name: provisioner-role
  apiGroup: rbac.authorization.k8s.io
